from sqlalchemy.orm import declarative_base, Mapped, mapped_column
from sqlalchemy import Integer, String, Date, Text

Base = declarative_base()

class BD8D(Base):
    __tablename__ = "bd8d"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    numero_reposicion: Mapped[str | None] = mapped_column(String(50))
    fecha_deteccion: Mapped[str | None]   = mapped_column(String(20))  # se puede normalizar a Date luego
    cliente: Mapped[str | None]           = mapped_column(String(200))
    pedido: Mapped[str | None]            = mapped_column(String(100))
    producto: Mapped[str | None]          = mapped_column(String(200))
    proceso: Mapped[str | None]           = mapped_column(String(200))
    area: Mapped[str | None]              = mapped_column(String(100))
    detectado_por: Mapped[str | None]     = mapped_column(String(200))
    nombre1: Mapped[str | None]           = mapped_column(String(200))
    departamento1: Mapped[str | None]     = mapped_column(String(200))
    nombre2: Mapped[str | None]           = mapped_column(String(200))
    departamento2: Mapped[str | None]     = mapped_column(String(200))
    nombre3: Mapped[str | None]           = mapped_column(String(200))
    departamento3: Mapped[str | None]     = mapped_column(String(200))
    que: Mapped[str | None]               = mapped_column(Text)
    cuando: Mapped[str | None]            = mapped_column(Text)
    donde: Mapped[str | None]             = mapped_column(Text)
    como: Mapped[str | None]              = mapped_column(Text)
    quien: Mapped[str | None]             = mapped_column(Text)
    cuanto_impacta: Mapped[str | None]    = mapped_column(Text)
    descripcion: Mapped[str | None]       = mapped_column(Text)
    accion_contencion: Mapped[str | None] = mapped_column(Text)
    fecha_contencion: Mapped[str | None]  = mapped_column(String(20))
    responsable_contencion: Mapped[str | None] = mapped_column(String(200))
    estatus_contencion: Mapped[str | None]     = mapped_column(String(100))
    por_que1: Mapped[str | None] = mapped_column(Text)
    por_que2: Mapped[str | None] = mapped_column(Text)
    por_que3: Mapped[str | None] = mapped_column(Text)
    por_que4: Mapped[str | None] = mapped_column(Text)
    por_que5: Mapped[str | None] = mapped_column(Text)
    causa_raiz: Mapped[str | None]        = mapped_column(Text)
    accion_correctiva: Mapped[str | None] = mapped_column(Text)
    fecha_correctiva: Mapped[str | None]  = mapped_column(String(20))
    responsable_correctiva: Mapped[str | None] = mapped_column(String(200))
    estatus_correctiva: Mapped[str | None]     = mapped_column(String(100))
    accion_preventiva: Mapped[str | None]      = mapped_column(Text)
    fecha_cierre: Mapped[str | None]           = mapped_column(String(20))
    responsable_auditar: Mapped[str | None]    = mapped_column(String(200))
    aprobo: Mapped[str | None]                 = mapped_column(String(100))

class CAPA(Base):
    __tablename__ = "bdcapa"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    numero_capa: Mapped[str | None]       = mapped_column(String(50))
    estatus: Mapped[str | None]           = mapped_column(String(100))
    fecha_creacion: Mapped[str | None]    = mapped_column(String(20))
    numero_reposicion: Mapped[str | None] = mapped_column(String(50))
    fecha_albaran: Mapped[str | None]     = mapped_column(String(20))
    pedido_origen: Mapped[str | None]     = mapped_column(String(100))
    nombre_pedido: Mapped[str | None]     = mapped_column(String(200))
    cliente: Mapped[str | None]           = mapped_column(String(200))
    comercial: Mapped[str | None]         = mapped_column(String(200))
    tecnico: Mapped[str | None]           = mapped_column(String(200))
    incidencia: Mapped[str | None]        = mapped_column(String(200))
    responsable: Mapped[str | None]       = mapped_column(String(200))
    accion_contencion: Mapped[str | None] = mapped_column(Text)
    accion_correccion: Mapped[str | None] = mapped_column(Text)
    desc_causa_resumida: Mapped[str | None] = mapped_column(Text)
    euro_reposicion: Mapped[str | None]   = mapped_column(String(50))
    euro_devolucion: Mapped[str | None]   = mapped_column(String(50))
    enlace_informe_8d: Mapped[str | None] = mapped_column(Text)
    matricula: Mapped[str | None]         = mapped_column(String(100))